
services:
  # MySQL Service
#  mysql:
#    image: mysql:8.0 # Use a stable MySQL version
#    container_name: mysql
#    environment:
#      MYSQL_DATABASE: productrateplanservice
#      MYSQL_ROOT_PASSWORD: P4ssword! # Root user password
#    ports:
#      - "3312:3306"
#    networks:
#      - db-network
#    restart: always

  # PostgreSQL Service
  postgres:
    image: postgres:15 # Use a stable PostgreSQL version
    container_name: postgres
    environment:
      POSTGRES_DB: productrateplanservice
      POSTGRES_USER: root
      POSTGRES_PASSWORD: P4ssword! # Root user password
    ports:
      - "5433:5432"
    networks:
      - db-network
    restart: always

  # Application Service
  app:
    build: .
    container_name: productrateplanservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/productrateplanservice
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=P4ssword!
    depends_on:
      - postgres
    networks:
      - db-network
    restart: always

networks:
  db-network:
    driver: bridge
